---
openapi: 3.1.0

info:
    title: IaC API
    description: IaC API
    version: 1.0.0

servers:
    - url: http://localhost:3000
    - url: http://{hostname}:{port}/
      description: "..."
      variables:
          base:
              enum:
                  - ''
                  - v1
                  - v2
                  - api
              default: ''
          hostname:
              enum:
                  - localhost
              default: localhost
          port:
              enum:
                  - '8443'
                  - '443'
                  - '3000'
                  - '80'
              default: '3000'
          protocol:
              enum:
                  - http
                  - https
                  - git
              default: http

paths:
    "/":
        get:
            summary: 'GET '
            responses:
                '200':
                    description: OK
    "/aws/lambda/functions/filter/environment-variables/{environment-variable}":
        get:
            summary: GET aws/lambda/functions/filter/environment-variables/{environment-variable}
            responses:
                '200':
                    description: OK
            parameters:
                - "$ref": "#/components/parameters/environment-variable"
    "/aws/lambda/functions/{configuration-filter}":
        get:
            summary: GET aws/lambda/functions/{lambda-function}
            parameters:
                - "$ref": "#/components/parameters/configuration"
            responses:
                '200':
                    description: OK
    "/aws/lambda/functions":
        get:
            summary: GET aws/lambda/functions
            responses:
                '200':
                    description: OK
    "/aws/lambda":
        get:
            summary: GET aws/lambda
            responses:
                '200':
                    description: OK
    "/aws":
        get:
            summary: GET aws
            responses:
                '200':
                    description: OK
    "/test":
        get:
            summary: GET test
            responses:
                '200':
                    description: OK
    "/utility/health":
        get:
            summary: GET utility/health
            responses:
                '200':
                    description: OK
    "/utility/awaitable":
        get:
            summary: GET utility/awaitable
            responses:
                '200':
                    description: OK
    "/schema":
        get:
            summary: GET schema
            responses:
                '200':
                    description: OK
    "/schema/typescript":
        get:
            summary: GET schema/typescript
            responses:
                '200':
                    description: OK

components:
    schemas:
        Error:
            type: string
        Empty:
            type: string
    parameters:
        environment-variable:
            name: environment-variable
            in: path
            description: An arbitrary required path-related string
            required: true
            schema:
                type: string
        configuration:
            name: configuration-filter
            in: path
            description: A Path Filter used via Lambda Function Endpoint(s)
            required: true
            schema:
                type: string
    responses:
        '200':
            description: 200 OK
            headers:
                Content-Type:
                    schema:
                        type: string
                        default: Application/JSON
                    style: simple
                    required: true
        '405':
            description: Method Not Allowed
            content:
                "*/*": {}
                application/json: {}
                application/xml: {}
    securitySchemes:
        Basic:
            type: http
            scheme: basic
            description: "..."
        API:
            type: apiKey
            name: X-API-Key
            in: header
        JWT:
            type: http
            scheme: bearer
            bearerFormat: JWT
            description: "..."
        Flow:
            type: oauth2
            flows:
                implicit:
                    authorizationUrl: https://example.com/api/oauth/dialog
                    refreshUrl: ''
                    scopes:
                        write:pets: modify pets in your account
                        read:pets: read your pets
                authorizationCode:
                    authorizationUrl: https://example.com/api/oauth/dialog
                    tokenUrl: https://example.com/api/oauth/token
                    scopes:
                        write:pets: modify pets in your account
                        read:pets: read your pets
security:
    - {}
    - Basic: []
    - API: []
    - JWT: []
